services:
  odasrv:
    image: ghcr.io/frantjc/odasrv:${ODAMEX_VERSION:-stable}
    build:
      context: .
      dockerfile: ${ODAMEX_SRC:-branch}.Dockerfile
      args:
        ODAMEX_VERSION: ${ODAMEX_VERSION:-stable}
    command:
      - -config
      - /usr/local/etc/odamex/odasrv.cfg
    ports:
      - 10666:10666/udp
    volumes:
      - ./odasrv.cfg:/usr/local/etc/odamex/odasrv.cfg
