---
apiVersion: v1
kind: ConfigMap
metadata:
  name: odamex
data:
  odasrv.cfg: |
    set join_password ""
---
apiVersion: v1
kind: Service
metadata:
  name: odamex
spec:
  type: LoadBalancer
  ports:
    - port: 10666
      targetPort: 10666
      protocol: UDP
  selector:
    app.kubernetes.io/name: odamex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odamex
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: odamex
  template:
    metadata:
      labels:
        app.kubernetes.io/name: odamex
    spec:
      volumes:
        - name: wads
          hostPath:
            path: /path/to/wads
            type: Directory
        - name: cfg
          configMap:
            name: odamex
      containers:
        - name: odasrv
          image: ghcr.io/frantjc/odasrv:10.6.0
          args:
            - -config
            - /usr/local/etc/odamex/odasrv.cfg
            - -waddir
            - /usr/local/games/wads
            - -iwad
            - mywad.wad
          volumeMounts:
            - name: wads
              mountPath: /usr/local/games/wads
            - name: cfg
              mountPath: /usr/local/etc/odamex
