name: CI
on:
  workflow_dispatch:
    inputs:
      version:
        description: Odamex version.
        required: true
        default: stable
      source:
        description: Odamex source.
        required: true
        default: branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v6
        with:
          load: true
          file: ${{ inputs.source || 'branch' }}.Dockerfile
          build-args: |
            ODAMEX_VERSION=${{ inputs.version || 'stable' }}
