name: CI
on:
  workflow_dispatch:
    inputs:
      version:
        description: Odamex version.
        required: true
        default: 11.0.0
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v6
        with:
          load: true
          build-args: |
            ODAMEX_VERSION=${{ inputs.version || '11.0.0' }}
