name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Odamex version.
        required: true
        default: stable
      version:
        description: Odamex source.
        required: true
        default: branch
permissions:
  packages: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{ inputs.source }}.Dockerfile
          build-args: |
            ODAMEX_VERSION=${{ inputs.version }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/odasrv:${{ inputs.version }}
